service: basic-serverless-lambda-python

provider:
  name: aws
  runtime: python
  stage: dev
  region: eu-west-2

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  theLambda:
  name: lambda-Vistor
  handler: lambda.lambda_handler 
  description: lambda-Vistor-Counter
  timeout: 6
  memorySize: 128
  package:
    patterns: 
      - "!node_modules/**"
      - "!yarn.lock"
      - "!package-loc.json"
      - "!package.json"